name: CD Pipeline

on:
  workflow_run:
    workflows: [CI Pipeline]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      (
        github.event.workflow_run.head_branch == 'main' ||
        github.event.workflow_run.head_branch == 'develop'
      )

    steps:
      - name: Deploy a Vercel
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
          HOOK_MAIN: ${{ secrets.VERCEL_DEPLOY_HOOK }}
          HOOK_DEVELOP: ${{ secrets.VERCEL_DEPLOY_HOOK_DEVELOP }}
        run: |
          if [ "$BRANCH" = "main" ]; then
            HOOK="$HOOK_MAIN"
          else
            HOOK="$HOOK_DEVELOP"
          fi

          curl --fail --show-error --request POST "$HOOK"

